### ISSUE TITLE
Hello  Support for Continue Generating?

### ISSUE THREAD

**Issue by zdwork** [drorm/gish#20]

**Comment by drorm** [comment]
Please provide additional information. I can't tell what you're asking for.

**Comment by zdwork** [comment]
![image](https://github.com/drorm/gish/assets/24469374/b1d6cd5d-95ec-4c72-ad4d-846040b9dda7)


The official ui function of openai

**Comment by drorm** [comment]
I see. I haven't used the UI much so I didn't see this new functionality. 
1. Have you tried it? Does it work well for you? Other people say it doesn't work well: https://community.openai.com/t/continue-generating-seems-broken/219379
2. Can you try to do "gish -c continue" and see if it tells you that you're using too many tokens?
3. One other option is to to use the GPT4 larger models like gpt4 8K or 32K
From my side, I don't think there's much I can do because the API doesn't provide hooks to do "continue"
